fieldLayouts:
  4debbbc8-8e32-414b-b8ef-df1bf3ccf457:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cfda38b3-54d3-4229-b4bc-7114b0932cde
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 761f596d-933b-4a4c-b5c8-0581c38d822d
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: 00885ec1-1272-40f5-b824-069712416b50 # Home
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
