fieldLayouts:
  7ab08eb5-45f5-4d5c-b8b6-79e869234fb7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 01078df6-7542-4696-aca6-ac33f8840c21
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 74f6c850-cba2-46b8-b972-12b405727dbb # Redactor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a4ae417-b0ed-4118-8d65-5b223eac51bf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bf92a2db-2903-468f-bd68-f61a743a0c30
        userCondition: null
handle: lesson
hasTitleField: true
name: Lesson
section: 9b41905c-1194-4d27-8f5f-afb4ccfb6a18 # Courses Structure
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
