fieldLayouts:
  4debbbc8-8e32-414b-b8ef-df1bf3ccf457:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cfda38b3-54d3-4229-b4bc-7114b0932cde
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c32a631a-0aee-45aa-a428-01aaa1231be6 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6491207b-a005-4cda-b7af-06561489d125
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c94ef32-b523-4f2c-9b33-6a6a88e9071b # Tagline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d98190f8-7ad9-4543-a2ba-6cf2e4b0c4b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb874278-0da4-4d05-906b-675ebd60a53b # cards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1a1e00b-bd4a-4c67-a2eb-d8383ba36082
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 761f596d-933b-4a4c-b5c8-0581c38d822d
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 00885ec1-1272-40f5-b824-069712416b50 # Home
sortOrder: 1
titleFormat: Home
titleTranslationKeyFormat: null
titleTranslationMethod: site
