defaultPlacement: end
enableVersioning: true
handle: courses
name: Courses
propagationMethod: all
siteSettings:
  7003e51a-380b-45ff-b5c7-8170a7148cc5: # StageCraft
    enabledByDefault: true
    hasUrls: true
    template: one_course/index.twig
    uriFormat: 'courses/{slug}'
structure:
  maxLevels: null
  uid: 8e5d7dde-97ef-4fcd-9f58-0f7e63c6efee
type: structure
