defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  7003e51a-380b-45ff-b5c7-8170a7148cc5: # StageCraft
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
